#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}
unset($file);

use IrfanTOOR\Console\Command;
use IrfanTOOR\Console\ShellCommand;

class IE extends Command
{
    function __construct()
    {
        $this->help = [
            'IE Command',
            'app:create' => 'Creates a small app',
            'app:serve'  => 'Serves the app on localhost:8000',
            'test'       => 'Tests Irfan\'s Engine',
        ];
        
        parent::__construct();
    }
    
    function app_create()
    {
        if (file_exists('app.php')) {
            $this->writeln("Application already exists", 'error');
        } else {
            file_put_contents('app.php', file_get_contents("examples/app.php"));
            $this->writeln("Application created! serve it on localhost:8000 using:", 'green');
            $this->writeln('$ ./ie app:serve', 'yellow');
        }
    }
    
    function app_serve()
    {
        if (file_exists('app.php')) {
            system('php -S localhost:8000 app.php');
        } else {
            $this->writeln("create an application first, using:", 'error');
            $this->writeln('$ ./ie app:create', 'yellow');
        }
    }
    
    function test()
    {
        $cmd = new ShellCommand();
        $cmd->execute('vendor/bin/phpunit --testdox');
        $this->writeln($cmd->output());
    }
}

$cmd = new IE;
$cmd->run();
